/**
 * Base-form verbs that mark the start of an instruction.
 *
 * PROVENANCE: this is an **implementation assumption**, not normative material. The list is
 * ordinary general and technical English action vocabulary chosen by the author of this package.
 * It is not derived from, and does not reproduce, any controlled-language dictionary.
 *
 * The list exists to answer one question: "does this passage begin by telling the reader to do
 * something?" It is deliberately over-inclusive on unambiguous action verbs and excludes verbs
 * whose base form is a common noun (`file`, `place`, `order`, `plan`, `state`, `test`, `mount`,
 * `power`, `contact`, `access`, `report`, `label`, `mark`, `screen`) because those produce
 * frequent misclassification of descriptive sentences.
 *
 * As of the `compromise` integration (`src/core/pos-tags.ts`), this list is no longer consulted
 * as a `Set.has()` membership test anywhere outside that module. Its role changed to:
 *  1. a domain lexicon taught to `compromise` via `addWords`, so `compromise`'s own
 *     context-sensitive tagger can recognise these words as verbs (`compromise`'s stock
 *     general-English lexicon does not know `torque`, `flash`, `ping`, `source`, `sync`,
 *     `query`, `rebase`, `unset`, `serialise` and others here as verbs — confirmed directly);
 *  2. a fallback for the rare case where `compromise`'s tokenisation of a sentence does not align
 *     with this project's own word tokeniser, so a lookup miss degrades to the old behaviour
 *     instead of silently doing nothing.
 * The words themselves, and their documented exclusions above, are unchanged — only how they are
 * consumed changed. Noun/verb disambiguation for an ambiguous word (`record`, `file`, `access`,
 * `test`, `set` … still tag as `Noun` in a noun context and `Verb` in a verb context) is now
 * handled by `compromise`'s grammar, not by this list.
 */
export const IMPERATIVE_VERBS: ReadonlySet<string> = new Set([
  // generic action
  'add',
  'adjust',
  'align',
  'apply',
  'assemble',
  'attach',
  'avoid',
  'calibrate',
  'change',
  'check',
  'choose',
  'clean',
  'clear',
  'click',
  'close',
  'compare',
  'complete',
  'configure',
  'confirm',
  'connect',
  'continue',
  'copy',
  'create',
  'cut',
  'define',
  'delete',
  'depress',
  'detach',
  'disable',
  'disconnect',
  'discard',
  'dismantle',
  'do',
  'download',
  'drain',
  'edit',
  'enable',
  'engage',
  'enter',
  'examine',
  'execute',
  'extract',
  'fasten',
  'fill',
  'find',
  'finish',
  'fit',
  'flash',
  'flush',
  'follow',
  'format',
  'give',
  'grease',
  'hold',
  'identify',
  'ignore',
  'increase',
  'decrease',
  'insert',
  'inspect',
  'install',
  'isolate',
  'keep',
  'lift',
  'load',
  'lock',
  'loosen',
  'lower',
  'lubricate',
  'make',
  'measure',
  'move',
  'obey',
  'open',
  'operate',
  'paste',
  'perform',
  'press',
  'prepare',
  'prevent',
  'pull',
  'purge',
  'push',
  'put',
  'read',
  'reboot',
  'rebuild',
  'record',
  'refer',
  'reinstall',
  'release',
  'remove',
  'repair',
  'repeat',
  'replace',
  'reset',
  'restart',
  'restore',
  'retain',
  'return',
  'rotate',
  'run',
  'save',
  'seal',
  'secure',
  'select',
  'send',
  'separate',
  'set',
  'shut',
  'specify',
  'start',
  'stop',
  'store',
  'switch',
  'take',
  'tighten',
  'torque',
  'touch',
  'turn',
  'type',
  'uninstall',
  'unlock',
  'unplug',
  'unzip',
  'update',
  'upgrade',
  'upload',
  'use',
  'verify',
  'wait',
  'wear',
  'withdraw',
  'write',
  // software specific
  'build',
  'commit',
  'compile',
  'deploy',
  'export',
  'import',
  'initialise',
  'initialize',
  'invoke',
  'launch',
  'merge',
  'migrate',
  'navigate',
  'pass',
  'ping',
  'publish',
  'pull',
  'query',
  'rebase',
  'redeploy',
  'reload',
  'rename',
  'replicate',
  'request',
  'rerun',
  'restrict',
  'revoke',
  'rollback',
  'scroll',
  'serialise',
  'serialize',
  'sign',
  'source',
  'submit',
  'subscribe',
  'sync',
  'terminate',
  'unset',
  'validate',
]);
